# Generated by Django 3.1.7 on 2021-03-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210317_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inputFile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
